apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mw.fullname" . }}
  labels:
{{ include "mw.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mw.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mw.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "mw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: mediawiki
          hostPath:
            path: /srv/mediawiki
        - name: ca
          configMap:
            name: kube-root-ca.crt
        - name: l10n
          hostPath:
            path: {{ .Values.l10n.cache.nodePath }}
            type: DirectoryOrCreate
      initContainers:
        # Ensure that l10n.cache.containerPath is writable by www-data
        - name: {{ .Chart.Name }}-init-l10n-dir
          securityContext:
            runAsUser: 0
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "chown", "www-data:", {{ .Values.l10n.cache.containerPath }} ]
          volumeMounts:
            - name: l10n
              mountPath: {{ .Values.l10n.cache.containerPath }}

        - name: {{ .Chart.Name }}-init-l10n
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ /init-l10n-locked.sh ]
          env:
            - name: INIT_L10N_CACHE_DIR
              value: {{ .Values.l10n.cache.containerPath }}
            - name: INIT_L10N_WIKIVERSIONS_JSON
              value: {{ .Values.wikiversionsJson | required "wikiversionsJson value must be set" }}
            - name: INIT_L10N_LANGS
              value: {{ .Values.l10n.cache.langs | join "," | quote }}
            - name: INIT_L10N_THREADS
              value: {{ .Values.l10n.cache.rebuildThreads | quote }}
          volumeMounts:
            - name: mediawiki
              mountPath: /srv/mediawiki
            - name: ca
              mountPath: /usr/local/share/ca-certificates
              readOnly: true
            - name: l10n
              mountPath: {{ .Values.l10n.cache.containerPath }}
          resources:
            requests:
              cpu: 1
              memory: {{ .Values.l10n.cache.rebuildThreads | mul 150 }}Mi
            limits:
              cpu: {{ .Values.l10n.cache.rebuildThreads }}
              memory: {{ .Values.l10n.cache.rebuildThreads | mul 150 }}Mi

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: mediawiki
              mountPath: /srv/mediawiki
            - name: ca
              mountPath: /usr/local/share/ca-certificates
              readOnly: true
            - name: l10n
              mountPath: {{ .Values.l10n.cache.containerPath }}
              readOnly: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /wiki/Main_Page
              port: http
              httpHeaders:
                - name: Host
                  value: en.wikipedia.org
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
